name: search
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  json_annotation: ^4.6.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.2
  mocktail: ^0.3.0

flutter:
  assets:
    - assets/json/
